# GoHighLevel API
GOHIGHLEVEL_API_KEY=your_ghl_private_integration_token_here
GOHIGHLEVEL_LOCATION_ID=your_ghl_location_id_here

# Zoho API
ZOHO_CLIENT_ID=your_zoho_client_id_here
ZOHO_CLIENT_SECRET=your_zoho_client_secret_here
ZOHO_REFRESH_TOKEN=your_zoho_refresh_token_here

# Google Sheets
GOOGLE_CREDENTIALS=credentials.json
SPREADSHEET_ID=your_spreadsheet_id_here
SHEET_NAME=suppression register

# Run mode
DRY_RUN=false
